TRUNCATE TABLE kitchens CASCADE;
TRUNCATE TABLE menu_items CASCADE;
TRUNCATE TABLE order_users CASCADE;
TRUNCATE TABLE order_items CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE authorities CASCADE;